export default Type = {
  TODO_ADD: "TODO_ADD",
  TODO_DELETE: "TODO_DELETE",
  TODO_UPDATE: "TODO_UPDATE",
  CHANGE_SCREEN: "CHANGE_SCREEN",
  FETCH_TODOS: "FETCH_TODOS",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_LOADER: "SHOW_LOADER",
  FETCH_ERROR: "FETCH_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  SHOW_ERROR: "FETCH_ERROR",
  CLEAR_FETCH_ERROR: "CLEAR_FETCH_ERROR"
};
